-- Run this script in your Supabase SQL Editor to create the sensor_readings table

create table if not exists public.sensor_readings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Device Identity
    device_id text not null,
    
    -- Raw Sensor Data
    temperature numeric not null,
    humidity numeric not null,
    soil_moisture numeric not null,
    
    -- Simulated or Actual NPK & pH data
    ph numeric not null,
    nitrogen numeric not null,
    phosphorus numeric not null,
    potassium numeric not null,
    
    -- Flag to know if NPK & pH were simulated by VoltVortex
    simulated boolean not null default true,
    
    -- Analytics Results
    stress_risk numeric not null,
    anomaly_detected boolean not null default false
);

-- Optional: Add indexes for faster querying
create index idx_sensor_readings_device_id on public.sensor_readings (device_id);
create index idx_sensor_readings_created_at on public.sensor_readings (created_at desc);

-- Optional: Set up Row Level Security (RLS)
-- If your backend uses the Service Role Key, it will bypass RLS automatically.
alter table public.sensor_readings enable row level security;

-- Allow anonymous or authenticated inserts if using ANON key (Uncomment if needed)
-- create policy "Allow anon inserts" on public.sensor_readings for insert with check (true);
-- create policy "Allow anon reads" on public.sensor_readings for select using (true);
